---
name: Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test project
    steps:
      - name: Source checkout
        uses: actions/checkout@v2.3.4

      - name: Cache maven repository
        uses: actions/cache@v2.1.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Set up Java 16
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 16

      - name: Test the project with maven
        run: mvn clean test
